dbt_transformation_lcbo:
  target: dev
  outputs:
    dev:                          # your existing local target — leave as is
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      pass: Bhavik@7573073
      dbname: postgres
      schema: silver
      threads: 4
    docker:                       # THIS is for running inside the container
      type: postgres
      host: host.docker.internal
      port: 5432
      user: postgres
      pass: Bhavik@7573073
      dbname: postgres
      schema: silver
      threads: 4